#pragma once
#include <stdbool.h>
#include "usb-desc.h"

enum Usb_endpointOwner { USB_ENDP_OWNER_CPU, USB_ENDP_OWNER_USB };

enum Usb_endpointId {
  USB_ENDP_OUT_0 = 0,
  USB_ENDP_OUT_1,
  USB_ENDP_OUT_2,
  USB_ENDP_OUT_3,
  USB_ENDP_OUT_4,
  USB_ENDP_OUT_5,
  USB_ENDP_OUT_6,
  USB_ENDP_OUT_7,
  USB_ENDP_OUT_8,
  USB_ENDP_OUT_9,
  USB_ENDP_OUT_10,
  USB_ENDP_OUT_11,
  USB_ENDP_OUT_12,
  USB_ENDP_OUT_13,
  USB_ENDP_OUT_14,
  USB_ENDP_OUT_15,
  USB_ENDP_IN_0,
  USB_ENDP_IN_1,
  USB_ENDP_IN_2,
  USB_ENDP_IN_3,
  USB_ENDP_IN_4,
  USB_ENDP_IN_5,
  USB_ENDP_IN_6,
  USB_ENDP_IN_7,
  USB_ENDP_IN_8,
  USB_ENDP_IN_9,
  USB_ENDP_IN_10,
  USB_ENDP_IN_11,
  USB_ENDP_IN_12,
  USB_ENDP_IN_13,
  USB_ENDP_IN_14,
  USB_ENDP_IN_15
};

struct Usb_ownerChangeMask {
  uint32_t mask;
};
